# This is a basic workflow to help you get started with Actions

name: Push

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get code
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm rum lint
        
      - name: Test code
        run: npm run test
        
      - name: Build code
        run: npm run build
